creation_rules:
  - path_regex: appsettings
    encrypted_regex: '^(.*[Ss]ecret.*|.*[Pp]assword.*|.*[Kk]ey.*|.*[Tt]oken.*|ConnectionStrings)$'
    azure_keyvault: >-
      https://keyvault-ydv765mduoiws.vault.azure.net/keys/sops-key/78115f33e44a4e04a1e38cdb77044d04
    age: >-
      age1zxw4360l6a6fu6p9pxtes5jgn2xtsxema9zzauh2uy37pjkhf9vq0xuq98
