packages:
  - 'Sandbox.AngularWorkspace'
  - 'Sandbox.EndToEndTests'

catalog:
  '@stoplight/spectral-cli': '6.15.0'
  '@types/node': '24.10.0'
  'dotenv': '17.2.3'
  'jsdom': '27.1.0'
  'prettier': '3.6.2'
  'run-script-os': '1.1.6'
  'rxjs': '~7.8.2'
  'tslib': '2.8.1'
  'typescript': '5.9.3'
  'zod': '4.1.12'

catalogs:
  angular:
    '@angular/build': '21.0.1'
    '@angular/cli': '21.0.1'
    '@angular/common': '21.0.1'
    '@angular/compiler': '21.0.1'
    '@angular/compiler-cli': '21.0.1'
    '@angular/core': '21.0.1'
    '@angular/forms': '21.0.1'
    '@angular/platform-browser': '21.0.1'
    '@angular/router': '21.0.1'
    'angular-eslint': '20.5.1'
    'ng-packagr': '21.0.0'

  opentelemetry:
    '@opentelemetry/auto-instrumentations-web': '0.54.0'
    '@opentelemetry/context-zone': '2.2.0'
    '@opentelemetry/exporter-trace-otlp-proto': '0.208.0'
    '@opentelemetry/instrumentation': '0.208.0'
    '@opentelemetry/resources': '2.2.0'
    '@opentelemetry/sdk-trace-base': '2.2.0'
    '@opentelemetry/sdk-trace-web': '2.2.0'
    '@opentelemetry/semantic-conventions': '1.38.0'

  testing-library:
    '@testing-library/angular': '18.1.1'
    '@testing-library/jest-dom': '6.9.1'
    '@testing-library/user-event': '14.6.1'

  eslint:
    '@eslint/js': '9.39.1'
    'eslint': '9.39.1'
    'eslint-config-prettier': '10.1.8'
    'eslint-plugin-playwright': '2.3.0'
    'typescript-eslint': '8.46.3'

  playwright:
    '@playwright/test': '1.56.1'
    'playwright': '1.56.1'

  vitest:
    '@vitest/browser': '4.0.8'
    'vitest': '4.0.8'
