packages:
  - 'Sandbox.AngularWorkspace'
  - 'Sandbox.EndToEndTests'

catalog:
  '@stoplight/spectral-cli': '6.15.0'
  '@types/node': '24.10.10'
  'dotenv': '17.2.3'
  'jsdom': '28.0.0'
  'prettier': '3.8.1'
  'prettier-plugin-tailwindcss': '0.6.11'
  'run-script-os': '1.1.6'
  'rxjs': '~7.8.2'
  'tslib': '2.8.1'
  'typescript': '5.9.3'
  'zod': '4.3.6'

catalogs:
  angular:
    '@angular/build': '21.1.2'
    '@angular/cli': '21.1.2'
    '@angular/common': '21.1.2'
    '@angular/compiler': '21.1.2'
    '@angular/compiler-cli': '21.1.2'
    '@angular/core': '21.1.2'
    '@angular/forms': '21.1.2'
    '@angular/platform-browser': '21.1.2'
    '@angular/router': '21.1.2'
    'ng-packagr': '21.1.0'

  opentelemetry:
    '@opentelemetry/auto-instrumentations-web': '0.56.0'
    '@opentelemetry/context-zone': '2.5.0'
    '@opentelemetry/exporter-trace-otlp-proto': '0.211.0'
    '@opentelemetry/instrumentation': '0.211.0'
    '@opentelemetry/resources': '2.5.0'
    '@opentelemetry/sdk-trace-base': '2.5.0'
    '@opentelemetry/sdk-trace-web': '2.5.0'
    '@opentelemetry/semantic-conventions': '1.39.0'

  testing-library:
    '@testing-library/angular': '19.0.0'
    '@testing-library/jest-dom': '6.9.1'
    '@testing-library/user-event': '14.6.1'

  eslint:
    '@eslint/js': '9.39.2'
    'eslint': '9.39.2'
    'angular-eslint': '21.2.0'
    'eslint-config-prettier': '10.1.8'
    'eslint-plugin-playwright': '2.5.1'
    'typescript-eslint': '8.54.0'

  playwright:
    '@playwright/test': '1.58.1'
    'playwright': '1.58.1'

  vitest:
    '@vitest/browser': '4.0.18'
    '@vitest/browser-playwright': '4.0.18'
    '@vitest/coverage-v8': '4.0.18'
    '@vitest/ui': '4.0.18'
    'vitest': '4.0.18'
