storage:
  tsdb:
    out_of_order_time_window: 15m
  # Remote storage configuration - https://thanos.io/tip/thanos/storage.md/

global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: minio-job-cluster
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets:
          - minio:9000
  - job_name: minio-job-bucket
    metrics_path: /minio/v2/metrics/bucket
    static_configs:
      - targets:
          - minio:9000
  - job_name: minio-job-resource
    metrics_path: /minio/v2/metrics/resource
    static_configs:
      - targets:
          - minio:9000
  - job_name: 'tempo'
    static_configs:
      - targets:
          - tempo:3200
  - job_name: blackbox-exporter
    static_configs:
      - targets:
          - blackbox:9115
  - job_name: blackbox
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://host.docker.internal:5499/health
          - http://host.docker.internal:5165/health
          - http://keycloak:9000/health
          - http://minio:9000/minio/health/live
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: host.docker.internal:9115
  - job_name: 'keycloak'
    static_configs:
      - targets:
          - keycloak:9000

otlp:
  promote_resource_attributes:
    - service.instance.id
    - service.name
    - service.namespace
    - service.version
