// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sandbox.Modules.CustomerManagement.Data;

#nullable disable

namespace Sandbox.Migrations.Migrations
{
    [DbContext(typeof(CustomerDbContext))]
    partial class CustomerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("CustomerManagement")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sandbox.Modules.CustomerManagement.Domain.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.ComplexProperty<Dictionary<string, object>>("Name", "Sandbox.Modules.CustomerManagement.Domain.Customer.Name#FullName", b1 =>
                        {
                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)");
                        });

                    b.HasKey("Id");

                    b.ToTable("Customers", "CustomerManagement");
                });

            modelBuilder.Entity("Sandbox.Modules.CustomerManagement.Domain.CustomerAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AddressType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.ComplexProperty<Dictionary<string, object>>("Address", "Sandbox.Modules.CustomerManagement.Domain.CustomerAddress.Address#Address", b1 =>
                        {
                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");
                        });

                    b.HasKey("Id");

                    b.ToTable("CustomerAddresses", "CustomerManagement");

                    b.HasDiscriminator<string>("AddressType").HasValue("CustomerAddress");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Sandbox.Modules.CustomerManagement.Domain.CustomerBillingAddress", b =>
                {
                    b.HasBaseType("Sandbox.Modules.CustomerManagement.Domain.CustomerAddress");

                    b.HasIndex("CustomerId");

                    b.HasDiscriminator().HasValue("Billing");
                });

            modelBuilder.Entity("Sandbox.Modules.CustomerManagement.Domain.CustomerShippingAddress", b =>
                {
                    b.HasBaseType("Sandbox.Modules.CustomerManagement.Domain.CustomerAddress");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("CustomerId");

                    b.HasDiscriminator().HasValue("Shipping");
                });

            modelBuilder.Entity("Sandbox.Modules.CustomerManagement.Domain.CustomerBillingAddress", b =>
                {
                    b.HasOne("Sandbox.Modules.CustomerManagement.Domain.Customer", null)
                        .WithMany("BillingAddresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sandbox.Modules.CustomerManagement.Domain.CustomerShippingAddress", b =>
                {
                    b.HasOne("Sandbox.Modules.CustomerManagement.Domain.Customer", null)
                        .WithMany("ShippingAddresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sandbox.Modules.CustomerManagement.Domain.Customer", b =>
                {
                    b.Navigation("BillingAddresses");

                    b.Navigation("ShippingAddresses");
                });
#pragma warning restore 612, 618
        }
    }
}
