// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ApiServiceSDK.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Command : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The billingAddress property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ApiServiceSDK.Models.Command.Command_billingAddress? BillingAddress { get; set; }
#nullable restore
#else
        public global::ApiServiceSDK.Models.Command.Command_billingAddress BillingAddress { get; set; }
#endif
        /// <summary>The firstName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FirstName { get; set; }
#nullable restore
#else
        public string FirstName { get; set; }
#endif
        /// <summary>The lastName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastName { get; set; }
#nullable restore
#else
        public string LastName { get; set; }
#endif
        /// <summary>The shippingAddress property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ApiServiceSDK.Models.Command.Command_shippingAddress? ShippingAddress { get; set; }
#nullable restore
#else
        public global::ApiServiceSDK.Models.Command.Command_shippingAddress ShippingAddress { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ApiServiceSDK.Models.Command"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ApiServiceSDK.Models.Command CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ApiServiceSDK.Models.Command();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "billingAddress", n => { BillingAddress = n.GetObjectValue<global::ApiServiceSDK.Models.Command.Command_billingAddress>(global::ApiServiceSDK.Models.Command.Command_billingAddress.CreateFromDiscriminatorValue); } },
                { "firstName", n => { FirstName = n.GetStringValue(); } },
                { "lastName", n => { LastName = n.GetStringValue(); } },
                { "shippingAddress", n => { ShippingAddress = n.GetObjectValue<global::ApiServiceSDK.Models.Command.Command_shippingAddress>(global::ApiServiceSDK.Models.Command.Command_shippingAddress.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::ApiServiceSDK.Models.Command.Command_billingAddress>("billingAddress", BillingAddress);
            writer.WriteStringValue("firstName", FirstName);
            writer.WriteStringValue("lastName", LastName);
            writer.WriteObjectValue<global::ApiServiceSDK.Models.Command.Command_shippingAddress>("shippingAddress", ShippingAddress);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::ApiServiceSDK.Models.BillingAddress"/>, <see cref="global::ApiServiceSDK.Models.Command_billingAddressMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Command_billingAddress : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::ApiServiceSDK.Models.BillingAddress"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::ApiServiceSDK.Models.BillingAddress? BillingAddress { get; set; }
#nullable restore
#else
            public global::ApiServiceSDK.Models.BillingAddress BillingAddress { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::ApiServiceSDK.Models.Command_billingAddressMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::ApiServiceSDK.Models.Command_billingAddressMember1? CommandBillingAddressMember1 { get; set; }
#nullable restore
#else
            public global::ApiServiceSDK.Models.Command_billingAddressMember1 CommandBillingAddressMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::ApiServiceSDK.Models.Command.Command_billingAddress"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::ApiServiceSDK.Models.Command.Command_billingAddress CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::ApiServiceSDK.Models.Command.Command_billingAddress();
                if("BillingAddress".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.BillingAddress = new global::ApiServiceSDK.Models.BillingAddress();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CommandBillingAddressMember1 = new global::ApiServiceSDK.Models.Command_billingAddressMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(BillingAddress != null)
                {
                    return BillingAddress.GetFieldDeserializers();
                }
                else if(CommandBillingAddressMember1 != null)
                {
                    return CommandBillingAddressMember1.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(BillingAddress != null)
                {
                    writer.WriteObjectValue<global::ApiServiceSDK.Models.BillingAddress>(null, BillingAddress);
                }
                else if(CommandBillingAddressMember1 != null)
                {
                    writer.WriteObjectValue<global::ApiServiceSDK.Models.Command_billingAddressMember1>(null, CommandBillingAddressMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::ApiServiceSDK.Models.Command_shippingAddressMember1"/>, <see cref="global::ApiServiceSDK.Models.ShippingAddress"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Command_shippingAddress : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::ApiServiceSDK.Models.Command_shippingAddressMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::ApiServiceSDK.Models.Command_shippingAddressMember1? CommandShippingAddressMember1 { get; set; }
#nullable restore
#else
            public global::ApiServiceSDK.Models.Command_shippingAddressMember1 CommandShippingAddressMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::ApiServiceSDK.Models.ShippingAddress"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::ApiServiceSDK.Models.ShippingAddress? ShippingAddress { get; set; }
#nullable restore
#else
            public global::ApiServiceSDK.Models.ShippingAddress ShippingAddress { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::ApiServiceSDK.Models.Command.Command_shippingAddress"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::ApiServiceSDK.Models.Command.Command_shippingAddress CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::ApiServiceSDK.Models.Command.Command_shippingAddress();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CommandShippingAddressMember1 = new global::ApiServiceSDK.Models.Command_shippingAddressMember1();
                }
                else if("ShippingAddress".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ShippingAddress = new global::ApiServiceSDK.Models.ShippingAddress();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(CommandShippingAddressMember1 != null)
                {
                    return CommandShippingAddressMember1.GetFieldDeserializers();
                }
                else if(ShippingAddress != null)
                {
                    return ShippingAddress.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(CommandShippingAddressMember1 != null)
                {
                    writer.WriteObjectValue<global::ApiServiceSDK.Models.Command_shippingAddressMember1>(null, CommandShippingAddressMember1);
                }
                else if(ShippingAddress != null)
                {
                    writer.WriteObjectValue<global::ApiServiceSDK.Models.ShippingAddress>(null, ShippingAddress);
                }
            }
        }
    }
}
#pragma warning restore CS0618
