// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ApiServiceSDK.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Response : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The billingAddresses property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::ApiServiceSDK.Models.BillingAddress>? BillingAddresses { get; set; }
#nullable restore
#else
        public List<global::ApiServiceSDK.Models.BillingAddress> BillingAddresses { get; set; }
#endif
        /// <summary>The firstName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FirstName { get; set; }
#nullable restore
#else
        public string FirstName { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Id { get; set; }
#nullable restore
#else
        public UntypedNode Id { get; set; }
#endif
        /// <summary>The lastName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastName { get; set; }
#nullable restore
#else
        public string LastName { get; set; }
#endif
        /// <summary>The shippingAddresses property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::ApiServiceSDK.Models.ShippingAddress>? ShippingAddresses { get; set; }
#nullable restore
#else
        public List<global::ApiServiceSDK.Models.ShippingAddress> ShippingAddresses { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ApiServiceSDK.Models.Response"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ApiServiceSDK.Models.Response CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ApiServiceSDK.Models.Response();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "billingAddresses", n => { BillingAddresses = n.GetCollectionOfObjectValues<global::ApiServiceSDK.Models.BillingAddress>(global::ApiServiceSDK.Models.BillingAddress.CreateFromDiscriminatorValue)?.AsList(); } },
                { "firstName", n => { FirstName = n.GetStringValue(); } },
                { "id", n => { Id = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "lastName", n => { LastName = n.GetStringValue(); } },
                { "shippingAddresses", n => { ShippingAddresses = n.GetCollectionOfObjectValues<global::ApiServiceSDK.Models.ShippingAddress>(global::ApiServiceSDK.Models.ShippingAddress.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::ApiServiceSDK.Models.BillingAddress>("billingAddresses", BillingAddresses);
            writer.WriteStringValue("firstName", FirstName);
            writer.WriteObjectValue<UntypedNode>("id", Id);
            writer.WriteStringValue("lastName", LastName);
            writer.WriteCollectionOfObjectValues<global::ApiServiceSDK.Models.ShippingAddress>("shippingAddresses", ShippingAddresses);
        }
    }
}
#pragma warning restore CS0618
