FROM mcr.microsoft.com/devcontainers/dotnet:1-9.0
FROM mcr.microsoft.com/devcontainers/typescript-node:2-22-bookworm

COPY --from=mcr.microsoft.com/dotnet/nightly/sdk:10.0.100-preview.6 /usr/share/dotnet /usr/share/dotnet
