name: Setup pnpm
description: Setup pnpm in your GitHub Actions workflow

runs:
  using: 'composite'
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        package_json_file: './package.json'

    - name: Use Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: .node-version
        cache: 'pnpm'
        cache-dependency-path: '**/pnpm-lock.yaml'

    - name: Install pnpm dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
